[package]
name = "sepia"
version = "0.1.0"
authors = ["micah <micah@glowcoil.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
baseview = { git = "https://github.com/rustaudio/baseview" }
raw-gl-context = "0.1.2"
gl = "*"
